import { reply } from '../bot.js'

export default [
  {
    name: 'bantuan',
    aliases: ['help', 'menu'],
    permission: 'all',
    async run(sock, m) {
      const lines = [
        '*Bantuan Bot Laporan*',
        '',
        'Periode laporan: 1 minggu (Senin-Minggu), tenggat otomatis.',
        '',
        '!lapor <nama> - <keterangan>',
        '  Kirim laporan mingguanmu (keterangan boleh kosong)',
        '  Contoh: !lapor Budi - Menyelesaikan laporan mingguan',
        '',
        '!status',
        '  Lihat siapa yang sudah/belum lapor',
        '',
        '!check',
        '  (Admin) Lihat list siapa yang sudah/belum lapor (tanpa DM)',
        '',
        '!tenggat <hari> <jam:menit>',
        '  (Admin) Ubah tenggat. Contoh: !tenggat Jumat 21:00',
        '',
        '!reset',
        '  (Admin) Mulai periode baru sekarang (reset semua laporan)',
        '',
        '!reset <nama>',
        '  (Admin) Reset laporan 1 orang (bisa pakai nama/HP) supaya bisa lapor ulang',
        '',
        '!alert on / !alert off',
        '  (Admin) Nyalakan/matikan alert tenggat otomatis',
        '',
        '!alertdm <teks>',
        '  (Admin) Ubah teks DM alert. Variabel: {nama} {tenggat} {periode}',
        '  Lihat/balikin: !alertdm | !alertdm reset',
        '',
        '!join <link undangan grup>',
        '  (Admin) Bot gabung ke grup via link',
        '',
        '!leave',
        '  (Admin) Bot keluar dari grup ini',
        '',
        '!grup',
        '  (Admin) Daftar grup terdaftar',
        '',
        '!bantuan',
        '  Tampilkan bantuan ini',
        '',
        '*Otomatis:* kamu akan menerima DM pengingat sebelum tenggat,',
        'dan DM pemberitahuan setelah tenggat lewat bila belum lapor.',
        '',
        '*Admin:* semua perintah juga bisa dikirim dari DM (private chat) ke bot.',
      ]
      return reply(sock, m, lines.join('\n'))
    },
  },
]